# Generated by Django 2.0.2 on 2018-11-21 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '加入运动',
                'verbose_name_plural': '加入运动',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_type', models.BooleanField(verbose_name='是否发起人')),
                ('now_people', models.IntegerField(blank=True, null=True, verbose_name='已有人数')),
                ('address', models.CharField(max_length=100, verbose_name='约定地点')),
                ('sport_time', models.DateTimeField(verbose_name='约定运动开始时间')),
                ('sport_end_time', models.DateTimeField(default='', verbose_name='约定运动结束时间')),
                ('people_nums', models.IntegerField(verbose_name='人数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('status', models.IntegerField(choices=[(1, '已完成'), (2, '待人加入'), (3, '已取消')], verbose_name='状态')),
            ],
            options={
                'verbose_name': '发起约运动',
                'verbose_name_plural': '发起约运动',
            },
        ),
        migrations.CreateModel(
            name='Sport_Fav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '学生喜爱的运动',
                'verbose_name_plural': '学生喜爱的运动',
            },
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(max_length=30, verbose_name='运动项目')),
                ('image', models.ImageField(upload_to='sports/%Y/%m', verbose_name='运动封面图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Schools', verbose_name='学校')),
            ],
            options={
                'verbose_name': '运动项目',
                'verbose_name_plural': '运动项目',
            },
        ),
        migrations.AddField(
            model_name='sport_fav',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excersise.Sports', verbose_name='运动项目'),
        ),
    ]
