# Generated by Django 2.0.2 on 2018-11-21 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('excersise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport_fav',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schools.Schools', verbose_name='学校'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excersise.Sports', verbose_name='运动项目'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发起人'),
        ),
        migrations.AddField(
            model_name='joinschedule',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excersise.Schedule', verbose_name='加入的运动'),
        ),
        migrations.AddField(
            model_name='joinschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='sports',
            unique_together={('school', 'sport_name')},
        ),
        migrations.AlterUniqueTogether(
            name='sport_fav',
            unique_together={('student', 'sport')},
        ),
    ]
