# Generated by Django 2.0.2 on 2018-11-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='category_type',
            field=models.IntegerField(choices=[(1, '学校'), (2, '学院'), (3, '专业')], help_text='类目级别', verbose_name='类目级别'),
        ),
    ]
